[package]
name = "rusteye"
version = "0.1.0"
authors = ["Abdelrahman Kandil <abdelrahmankandil@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
